### ISSUE TITLE
Interlinear in another file

### ISSUE THREAD

**Issue by ghost** [erykjj/jwpublib#30]
Would it be possible to have a Strong's interlinear that doesn't eliminate the kingdom interlinear?

**Comment by erykjj** [comment]
Hi @SimoneAiello00 

I have tried, but it _seems_ the JW Library app is hard-coded to only present the **int** Bible in that two-line format (also the Pinyin Bible) :-(

I'll have another go at it in the future. Perhaps that has changed.

**Comment by erykjj** [comment]
But, personally, I don't miss the interlinear. Just add the KJS to the list of Bibles to compare and you have all the Greek _and_ Hebrew terms.

**Comment by SimoneAiello00** [comment]
Hi @erykjj, thanks for the reply ... and ... what if we made a text without any interlinear part? Would it be possible in your opinion? Because I like the kingdom interlinear ... because I like to read Greek ... but since you're at it ... would it be possible to make one entire Bible in Hebrew and then one entirely in Greek? Maybe we can find a text that is in the public domain ... would you know anything about it? One could create, without an interlinear part, a text containing the entire Scriptures in ancient Hebrew and then, another one, in ancient Greek ...

For the Scriptures in Greek it would be necessary to include the text of the LXX plus the Greek text of the Greek Scriptures, while for the Scriptures in Hebrew it would be necessary to include the Masoretic text plus a translation of the Greek Scriptures into ancient Hebrew, if you would like to do it ... I could give you a hand ... we should just make sure Jehovah bless the thing ... because ... actually these texts are often produced and distributed by the false religion ...

However, if we don't want to deal with all this mess we could maybe do, if you like to explain to me how to help, if you need a hand of course, to make a non-interlinear Bible, made entirely of Strong's numbers ... so we don't lose the kingdom interlinear ...

Thanks anyway for your great work, have a nice day, Simone

**Comment by erykjj** [comment]
Hi Simone,

First of all, please keep in mind this is a public tech forum.

I appreciate your ideas and suggestions. I don't see many wanting to _read_ the koine Greek text. And a Bible made just out of numbers... seems even less practical.

I will retry making KJS with another publication id, so that it can co-exist with the Interlinear, but in the future, and there is no guarantee it will work.

**Comment by SimoneAiello00** [comment]
Hi @erykjj, thanks for listening, but please, what do you mean by "First of all, please keep in mind this is a public tech forum". It kind of sounds like a scolding, can you be more specific please?

You removed part of my comment ... in the end they are opinions, I don't understand why you took it so hard ... and I don't understand why I should hide my opinions about religion ... if you think differently it's not a problem to me ... I simply expressed my opinions to you, I thought we thought the same way, that's why I allowed myself to be sincere, and regarding the opinions I express in public, I have nothing to be ashamed of ... 

But, anyway, If you cannot read ancient Greek, I can understand your reasons, but ... the Strong's numbers do not indicate the form of the lemma but only the lemma, and therefore they are not of much use to people who want to understand the text ... indeed, what is missing in Strong's numbers is the conjugation and declension... I don't know if you understand anything about linguistics ... but it's very important to people who read a text to see what kind of morphology a lemma has.

But I'm not sure I understand well. Do we have to use a publication ID to make this Bible with Strong's numbers? ... otherwise, if I can help you, you could use a generic ID, one for generic publications, like those you used to make publications that end up in the Guidelines ... like ... the Timeline of Bible History, the Bible Reading Schedules or the Hebrew and Greek Strong's dictionary ...

@erykjj, please, tell me if I said to you something unpleasant. I don't want to be unpleasant to you. When I talked about religion I was just being honest, I didn't want to be polemical towards anyone.

In any case, have a good day, Simone

PS

A Bible made entirely of Strong's numbers without the words can be useful however, in fact the Bible with Strong's numbers, together with the dictionary and concordance can be very useful tools,

Perhaps, if you can edit the Kingdom Interlinear, you could include, as the main text, the Greek text for the Greek Scriptures, and the KJV for the Hebrew Scriptures ... and then, as a secondary interlinear text, you could include Strong's numbers, I don't know if I explained myself well ... feel free to ask me for more if you want ...

**Comment by erykjj** [comment]
Simone,

It is not just about you and me. I wish to show respect for the sensibilities of others.

I cannot modify the Kingdom Interlinear version as I don't have the rights to it.

The Greek and Hebrew texts are freely available:
https://sourceforge.net/projects/zefania-sharp/files/Bibles/GRC/
https://sourceforge.net/projects/zefania-sharp/files/Bibles/HEB/

But, that is not on my list of projects. At this time.

The only way I could get KJS to display in the interlinear format is by giving it the "int" publication code - the same as the "official" Kingdom Interlinear. Otherwise, it only shows the King James Version text (with no Strong's numbers), which defeats the purpose. So, it has to be one or the other. For now. Maybe later I will try again with a different code and get it to work, so that the Kingdom Interlinear (int) and KJS can co-exist.

Have I explained myself?

**Comment by SimoneAiello00** [comment]
I'm sorry if I seemed insensitive towards others, obviously I didn't mean to.

But anyway ... if I may ask you, if I wanted to write a publication to insert into the JW Library ... how can I convert any file into a blob file to insert into the database file of the publication I want to write. I'm not an expert in databases and therefore I don't know how to manage blob files, can you give me some advice? who can I ask, what can I study ... do you know anything about it?

I mean, how did you manage to write these files that you uploaded to this repository, if I may ask you of course ... thanks in advance, have a good day, Simone

**Comment by erykjj** [comment]
Hi Simone,

Please show respect for me as well.
https://github.com/erykjj/jwpublib#jwpublib

Thank you and have a good day, too.

Eryk

**Comment by SimoneAiello00** [comment]
How would I have disrespected you?

**Comment by erykjj** [comment]
Please read the second paragraph in the project Readme that I linked in my reply. Thank you.

**Comment by erykjj** [comment]
> Would it be possible to have a Strong's interlinear that doesn't eliminate the kingdom interlinear?

Please check out the new format: https://github.com/erykjj/jwpublib#kjv-and-strongs-inlineinterlinear
