### ISSUE TITLE
Bible Reading Schedule missing Chronological section

### ISSUE THREAD

**Issue by joelynjellybean** [erykjj/jwpublib#46]
I just updated my BRS English from 1.4 to 3.2 and my chronological section has disappeared. I have the new thematic section but not the one I was using. Is it possible to have all 4 options? If so, please reinsert the chronological section. Also, is there a quick way to "uncheck all" items to reuse at the end of a schedule. I can uncheck them individually but that is very time-consuming. Thank you for all your hard work.

**Comment by erykjj** [comment]
Hi @joelynjellybean 
Looks like you've missed a few updates in-between :-)

The chronological schedule was incomplete and imprecise. That's why it was removed. A brother is working on an improved schedule, so (hopefully) it will be included in future updates.

As for unchecking, JW Library doesn't have any such "quick-wipe" option, but if you're not afraid of tech, you can use my [JWLManager app](https://github.com/erykjj/jwlmanager) to delete the annotations for BRS, or... do the inverse: unchecked means completed :-)

Eryk

**Comment by joelynjellybean** [comment]
Thanks for the response. I look forward to the new and improved schedule in
the future. Thanks for all you do with these add-ons. They are wonderful.

**Comment by erykjj** [comment]
Hi @joelynjellybean 

Due to being very busy, that chronological schedule that was in the works hasn't advanced much. So, I am looking for semi-tech-savvy volunteers to help. Would you be interested?

**Comment by joelynjellybean** [comment]
Yes, I would be interested. Not sure what is involved but if be happy to
help if I can.

**Comment by erykjj** [comment]
> Yes, I would be interested. Not sure what is involved but if be happy to help if I can.

Check your notifications ;-)

**Comment by joelynjellybean** [comment]
Notifications where? And I have my assembly this weekend and then will be
on vacation for a couple of weeks so it will be a bit before I can take a
look.
