### ISSUE TITLE
Errata in Fth

### ISSUE THREAD

**Issue by MisaelArciniega** [erykjj/jwpublib#54]
![Screenshot_20240913_162233_org jw jwlibrary mobile](https://github.com/user-attachments/assets/7708744b-1199-447e-b837-c2d54ec41778)
1 instead of I
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010001&par=28

![Screenshot_20240913_162216_org jw jwlibrary mobile](https://github.com/user-attachments/assets/6fb99f87-31c8-4999-b576-4eead01c64b2)

Lacking bible link
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010002&par=62

**Comment by erykjj** [comment]
Thank you, @MisaelArciniega !

Corrected.

Please report any and all such issues.

**Comment by glenmwright** [comment]
Do you prefer sharing as I am reading or one list of all?

It seems the elipsis character … was replaced with a dash - in a few occurrences so far.

![image](https://github.com/user-attachments/assets/b9d5100b-c34e-48a0-9bd3-5e110e0f449c)

![image](https://github.com/user-attachments/assets/6d57059a-e4a1-4515-8a21-72fbcfb661f6)

https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010001&par=31

![image](https://github.com/user-attachments/assets/e3c4ee15-06d2-4fda-9226-ae5b2210114c)

![image](https://github.com/user-attachments/assets/44cf4858-6945-4ec3-b805-9948578674e8)

https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010001&par=40

**Comment by erykjj** [comment]
Hi @glenmwright 

Yes, please report in this thread. That way others can see what was already reported.

The source was OCR of a poor-quality scan, and even though I and another brother already made _many_ corrections, obviously much still remains. So your proofreading and reporting is greatly appreciated!!

**Comment by glenmwright** [comment]
A few more for today. 

![image](https://github.com/user-attachments/assets/b7f8a3be-a9ec-4957-8955-9955af6a4b96)
![image](https://github.com/user-attachments/assets/705028b6-3510-4226-9b1c-f10949ab043e)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010001&par=41

![image](https://github.com/user-attachments/assets/075b527e-767f-4bd1-bab1-ddf3b44cc526)
![image](https://github.com/user-attachments/assets/0569d068-311c-43b3-be59-39b9d9b28d1a)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010002&par=62

![image](https://github.com/user-attachments/assets/f47fe102-1389-4a87-bad1-497fc39ac4ef)
![image](https://github.com/user-attachments/assets/7d2ab2e1-9fc6-4763-bb2b-348cfd2aa011)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010002&par=70

![image](https://github.com/user-attachments/assets/e48ef56d-ad1f-459c-8503-24bcb839d3fb)
![image](https://github.com/user-attachments/assets/fd6b7474-06fc-4b4b-81ee-4a6dfa7a5b98)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010003&par=38

![image](https://github.com/user-attachments/assets/d59f4995-c778-43e4-86b4-8beadb775b4e)
![image](https://github.com/user-attachments/assets/76e26eb9-f89e-4e5a-9ceb-b01bc96b5374)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010003&par=43

**Comment by glenmwright** [comment]
Here is what I found in Chapters 4 - 6 

A few more ellipsis are represented as dashes
![image](https://github.com/user-attachments/assets/349d9c73-28c5-4447-9a3e-a7e7dfe39adb)

![image](https://github.com/user-attachments/assets/01b11f71-751b-4f18-9dcb-882f5166829a)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010004&par=16

Should be **Unified**
![image](https://github.com/user-attachments/assets/8e8e77cf-2e22-4eb5-9f5f-7b11244b2550)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010004&par=34

"Turning point in our **time**"
![image](https://github.com/user-attachments/assets/00fbcd8d-7f16-4d30-9d7c-ff3dfadba622)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010004&par=50

Fix double quotes and open bracket
![image](https://github.com/user-attachments/assets/6f569b1e-68d8-46e5-a9c4-86aef59c47d4)
![image](https://github.com/user-attachments/assets/99c1d76f-571a-4f49-9384-982ea952e455)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010004&par=57

Should be, "I said:"
![image](https://github.com/user-attachments/assets/22da797a-0fce-4a26-be8c-0ebc16038afc)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010004&par=68

"**perhaps** I should relate"
![image](https://github.com/user-attachments/assets/adefaf28-ecac-47cf-9bb5-23026ec3ffea)

![image](https://github.com/user-attachments/assets/df0087f4-0e1f-4998-abd9-d5e3c0165631)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010005&par=12

Ellipsis
![image](https://github.com/user-attachments/assets/db5bca34-70d3-4181-912b-21bad4ca6b48)

![image](https://github.com/user-attachments/assets/a8252e8d-f88c-492a-bd50-2d2f70047e26)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010005&par=87

**Comment by erykjj** [comment]
Excellent work, @glenmwright !!

**Comment by glenmwright** [comment]
While I have read the printed book in the past, over the years I have tried to read a digital version only to find it very difficult due to inaccuracies and scanning defects. Thanks to everyone for making this as accurate as possible. 

Here are some corrections for Chapters 7 - 11.
"**all** the manuscript"
![image](https://github.com/user-attachments/assets/728a2d8d-829b-4fa1-ab98-f72a95194f53)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010007&par=39

remove dash and add ellipsis 
![image](https://github.com/user-attachments/assets/af757ff2-0d0b-4707-b6a7-eb6e01f924da)
![image](https://github.com/user-attachments/assets/eb9e32c8-ec4c-4a34-8bc8-98a37ae0523a)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010007&par=41

"**I** was given"
![image](https://github.com/user-attachments/assets/9609d4c8-8e68-4f65-bf55-2f5143716fec)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010007&par=90

"World War **I**" 
![image](https://github.com/user-attachments/assets/55c58df9-9c27-43af-a8b2-a033d569391d)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010008&par=30

remove dash and add ellipsis 
![image](https://github.com/user-attachments/assets/7d64e0ae-42a7-411d-b5e7-759498b64545)
![image](https://github.com/user-attachments/assets/5b09a531-bf4a-4943-9ff4-a18dc7e9490a)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010008&par=55

"**but** I have"
![image](https://github.com/user-attachments/assets/0379e367-d21c-4749-9d51-01c379ac204e)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010009&par=33

remove dash and add ellipsis 
![image](https://github.com/user-attachments/assets/555a94f0-7b37-4809-ab7f-69986c4db2bc)
![image](https://github.com/user-attachments/assets/536af095-801c-44d5-a95e-424f15c1fd20)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010009&par=54

Lowercase 'i'
![image](https://github.com/user-attachments/assets/9903f901-4ad9-41ae-9444-1893105674a9)
![image](https://github.com/user-attachments/assets/b5c23700-ad23-4a64-ba8e-9a27eebb686e)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010010&par=53

Uppercase 'I'
![image](https://github.com/user-attachments/assets/2672ab4f-3a5c-430d-a0cf-1879a4f2e6ee)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010011&par=13


![image](https://github.com/user-attachments/assets/2398f577-ff53-4774-88ff-4985b4053ef4)

**Comment by erykjj** [comment]
> While I have read the printed book in the past, over the years I have tried to read a digital version only to find it very difficult due to inaccuracies and scanning defects. Thanks to everyone for making this as accurate as possible.

Yes, many eyes make for better proofreading :-)

I have fixed everything reported up to this point.

**Comment by glenmwright** [comment]
Here are chapters 12-16.

Change comma to a period
![image](https://github.com/user-attachments/assets/671e45f7-d24d-4980-b574-774abb1cfe86)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010012&par=20

Lowercase "**I**"
![image](https://github.com/user-attachments/assets/e6ad5f23-4e21-4ff1-a5e1-bbe9de2fe1e6)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010012&par=30

Change comma to a period
![image](https://github.com/user-attachments/assets/d451d3d4-56fa-4764-9d04-52d794e92ff7)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010012&par=50

Change comma to a period
![image](https://github.com/user-attachments/assets/f1d5d670-68ed-4289-b9e1-1689d111e3e9)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010012&par=57

**Coining** should be coming. Change comma to period
![image](https://github.com/user-attachments/assets/c11f9aff-437e-44f6-81d3-ab56052e4a7c)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010012&par=58

Change comma to a period
![image](https://github.com/user-attachments/assets/d463d567-f091-46bf-933c-6f30a5ecb5e8)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010013&par=63

Change **bad** to had
![image](https://github.com/user-attachments/assets/9fa5b383-f002-47f1-b309-30512c4d31b1)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010014&par=7

Change "**our grew**" to "**outgrew**"
![image](https://github.com/user-attachments/assets/705f4346-363f-4c52-bff1-2bd847b3edc0)
![image](https://github.com/user-attachments/assets/1eb60d9d-1ea7-4778-b3db-2847503bad81)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010015&par=18

Change "**cat**" to "**eat**"
![image](https://github.com/user-attachments/assets/f948c3ed-9d7a-4e4b-90f9-097e15b78caa)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010015&par=34

Change comma to a period
![image](https://github.com/user-attachments/assets/540fe005-4777-4f19-a850-e0bfaf98ea6c)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010015&par=44

Change "**yon**" to "**you**"
![image](https://github.com/user-attachments/assets/602e1a02-ad59-4402-a119-5ffa397f94af)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010016&par=4

That is all I have seen on the first pass. 

Thanks again to everyone!

**Comment by glenmwright** [comment]
Found one more back in Chapter 1.

Change "**our**" to "**out**"
![image](https://github.com/user-attachments/assets/450919e0-8600-4f05-b4a4-66f78b68088a)
https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=47010001&par=19

**Comment by erykjj** [comment]
@glenmwright 
Are you planning a "second pass"?

**Comment by glenmwright** [comment]
I did a quick second pass and found that one addition. I think I have completed my quest ☺

**Comment by erykjj** [comment]
Well done!
I will release the corrected v2 soon :-)

**Comment by erykjj** [comment]
Thank you, @glenmwright & @MisaelArciniega !
v2 has been released with the changes you reported.

Please continue to report any further errors in this thread ;-)

**Comment by MisaelArciniega** [comment]
Thank to @glenmwright , he did everything
